[package]
name = "evscript"
version = "0.1.0"
edition = "2021"
description = "An extensible bytecode-based scripting engine"
homepage = "https://github.com/eievui5/evscript"
repository = "https://github.com/eievui5/evscript"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer"] }
regex = "1"
clap = { version = "4.4.2", features = ["derive"] }
codespan-reporting = "0.11.1"

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.20.0"
